luku1 = int(input("Syötä ensimmäinen luku: "))
luku2 = int(input("Syötä toinen luku: "))
luku3 = int(input("Syötä kolmas luku: "))
summa = luku1 + luku2 + luku3
tulo = luku1 * luku2 * luku3
ka = semma / 3
print(f"summa = {summa}")
print(f"tulo = {tulo}")
print(f"keskiarvo = {ke}")
